name: Build (libs + scrcpy-server)

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout (with submodules)
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      # scrcpy-server 用 Gradle/Java 构建，需要 JDK
      - name: Set up Java (for Gradle)
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Android SDK（构建 scrcpy-server.jar）
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # 可选：Gradle 缓存（加速 scrcpy-server 构建）
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 安装本地构建依赖：只在缺失时安装，避免与 pinned tap 冲突
      - name: Ensure build tools (no reinstall)
        run: |
          brew update
          for pkg in cmake ninja nasm yasm pkg-config autoconf automake libtool; do
            if ! brew list --versions "$pkg" >/dev/null 2>&1; then
              brew install "$pkg"
            else
              echo "✅ $pkg already installed: $(brew list --versions $pkg)"
            fi
          done
          # 如果仓库里有自带 formula（例如 porting/protobuf.rb），用相对路径安装更稳
          if [ -f "./porting/protobuf.rb" ]; then
            brew install ./porting/protobuf.rb || true
          fi
          cmake --version

      # 你要的步骤 1
      - name: Build libs
        run: make libs

      # 你要的步骤 2
      - name: Build scrcpy-server (Android jar)
        run: make -C porting scrcpy-server

      # 导出产物（主要是 scrcpy-server.jar）
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libs-and-scrcpy-server
          path: |
            **/scrcpy-server*.jar
            porting/**/build/libs/*.jar
